trigger:
  branches:
    include:
    - main
    - feature/rollout
    
pool:
  name: bac-ubuntu-b2s

resources:
  repositories:
    - repository: bancadigital-devsecops-templates
      type: git
      name: Banca-Digital/bancadigital-devsecops-templates
      ref: refs/tags/v0.3.141

variables:
  ECR_REGISTRY: '905418025699.dkr.ecr.us-east-1.amazonaws.com'
  SERVICE_NAME: 'investment-funds'
  CLUSTER_NAME: 'td-bac-cluster-desarrollo'
  AWS_DEFAULT_REGION: 'us-east-1'
  NS: 'td-bac-backend'
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64/'

jobs:
  - job: Build
    displayName: 'Build and Push Docker Image'
    pool:
      name: bac-ubuntu-b2s
    steps:
    - checkout: self
    
    - task: DownloadSecureFile@1
      name: m2
      displayName: 'Download M2 Configuration'
      inputs:
        secureFile: 'settings.xml'

    - script: |
        echo Copying $(m2.secureFilePath) to the maven directory...
        # mkdir -p ~/.m2
        sudo cp $(m2.secureFilePath) ~/.m2/settings.xml
        sudo chown -R AzDevOps:AzDevOps ~/
        ls -la ~/
        ls -la ~/.m2
        whoami
      displayName: 'Copy M2 Configuration'

    - template: ci/sonar-prepare.yml@bancadigital-devsecops-templates
      parameters:
        sonarProjectKey: 'bancadigital-ms-$(SERVICE_NAME)'
    
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package -DskipTests'
        javaHomeOption: 'Path'
        jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64/'
      displayName: 'Maven Package'
    
    - script: |
        echo "##vso[task.setvariable variable=PATH;]$JAVA_HOME/bin:$PATH"
      displayName: 'Add JAVA_HOME/bin to PATH'
    

    - template: ci/sonar-analyze.yml@bancadigital-devsecops-templates
      parameters:
        jdkversion: 'JAVA_HOME'  

    - template: ci/secret-files.yml@bancadigital-devsecops-templates
      
    - task: Docker@2
      inputs:
        repository: $(ECR_REGISTRY)/ms-$(SERVICE_NAME)
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: |
          $(Build.SourceBranchName)
          latest
          $(Build.BuildNumber)
      displayName: 'Build Docker Image'
    
    - template: ci/aws-iam-assume-role.yml@bancadigital-devsecops-templates
      parameters:
        SCRIPT: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $(ECR_REGISTRY)
    
    - task: Docker@2
      inputs:
        command: 'push'
        repository: $(ECR_REGISTRY)/ms-$(SERVICE_NAME)
        tags: |
          $(Build.SourceBranchName)
          latest
          $(Build.BuildNumber)
      displayName: 'Push Docker Image to AWS ECR'

  - job: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn: Build
    pool:
      name: bac-ubuntu-b2s
    steps:
    - template: ci/aws-iam-assume-role.yml@bancadigital-devsecops-templates
      parameters:
        SCRIPT: |
          aws eks list-clusters
          aws eks --region $(AWS_DEFAULT_REGION) update-kubeconfig --name $(CLUSTER_NAME)
          kubectl get all -n $(NS)
          input=${SERVICE_NAME}
          output=$(echo $input | cut -d'-' -f1)
          kubectl rollout restart deployment bac-$output-funds-deployment -n $(NS)