INVESTMENT_FUNDS_REMOTE_HOST=https://oauthservicedesa.baccredomatic.com/
USE_API-DOCS=true
USE_SWAGGER=true
DATAPOWER_SERVER=10.136.3.39
LIF_SERVICE_PATH=SAFI_Cliente_InformacionFondoPorCIF
LIF_OPERATION_CODE=SAFI_Cliente_InformacionFondoPorCIF
LIF_USER=001482789
LOBBY_FUNDS_TOKEN_HOST=https://oauthtokendesa.baccredomatic.com/token
AUTH_LIF_GRANT_TYPE=client_credentials
AUTH_LIF_SCOPE=/SAFI_Cliente_InformacionFondoPorCIF
AUTH_LIF_CLIENT_ID=bancaDigital
# OPENFGA CONFIGURATION
OPENFGA_ENVIRONMENT=https://bac-openfga-api.bancadigital.dev.aws.corp.redbac.com
OPENFGA_LIST_OBJECTS=/list-objects
WRAPPER_OPENFGA_BASE_URL=https://openfga.bancadigital.dev.aws.corp.redbac.com/openfga
WRAPPER_OPENFGA_USER_PATH=/user/{user}
# ENVIRONMENT
APP_ENVIRONMENT=DEV
#FeatureFlag
FF_OPENFGA=false
AWS_SECRET_INVESTMENT=aws-secretsmanager:SCRM-DTD-GED-OBS-DYNATRACE-DEV,aws-secretsmanager:SCRM-DTD-GED-MODELOPENFGA-DEV,aws-secretsmanager:SCRM-DTD-GED-AUTHCLIENT-DEV,aws-secretsmanager:SCRM-DTD-GED-AUTHLPFCLIENT-DEV,aws-secretsmanager:SCRM-DTD-GED-CERTIFICATEJKS1-DEV,aws-secretsmanager:SCRM-DTD-GED-CERTIFICATEPASS-DEV,aws-secretsmanager:SCRM-DTD-GED-INVESTMENTFUNDS-DP-DEV,aws-secretsmanager:SCRM-DTD-GED-KEYSTOREPASS-DEV,aws-secretsmanager:SCRM-DTD-GED-OPENFGA-DEV,aws-secretsmanager:SCRM-DTD-GED-POSTGRESINVESTMENTFUNDS-DEV,aws-secretsmanager:SCRM-DTD-GED-REDIS-DEV
#REDIS
REDIS_TTL=5000
REDIS_HOST=elc-dtd-gtd-redis-dev-us-east-1-nvmkry.serverless.use1.cache.amazonaws.com
REDIS_PORT=6379
#OBSERVABILITY
LOG_GROUP_NAME=/BancaMovil/Audit-log/LOG-DTD-GTD-BD-MS-LG-AUDIT-ZZ-DEV
PREFIX_LOG_STREAM_NAME=td-bac-investment-funds-ms
LOG_LEVEL_ROOT=INFO
LOG_LEVEL_BAC=DEBUG    
#POSTGRES
POSTGRES_HOST_K8=rds-aurora-postgresql-reg-cst-aliasaurora-us-east-1.cluster-c7igmk004dpo.us-east-1.rds.amazonaws.com
POSTGRES_PORT_K8=5432
#certs
#CERTIFICATES_PATH=/app/dev/certs
CERTIFICATES_PATH=C:\\Projects\\certs-local 1 1\\certs-local
#NEW ROAD
FUNDS_PER_CIF_ROAD=FW4
FW7_OAUTH_URL=https://mobiledev.services.corp.redbac.com/frw7/token
FW7_SERVICE_URL=https://mobiledev.services.corp.redbac.com/frw7/
FW4_OAUTH_URL=https://mobiledev.services.corp.redbac.com/frw4/token
FW4_SERVICE_URL=https://mobiledev.services.corp.redbac.com/frw4/
FUNDS_PER_CIF_NEW_ROAD_ENABLED=true
OAUTH=false
DATAPOWER_EMBEDDED_ERRORS=not found in service configuration table,Timeout from backend,no se encuentra en la tabla de configuracion
#RESILIENCE =================================================
#RESILIENCE - General
BULKHEAD_MAX_CONCURRENT_CALLS=2147483647
BULKHEAD_MAX_WAIT_DURATION=10000s
TIMEOUT_DURATION=15s
SLIDING_WINDOW_SIZE_CR=10
MINIMUM_NUMBER_OF_CALLS_CR=10
FAILURE_RATE_THRESHOLD_CR=50
PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE_CR=5
WAIT_DURATION_IN_OPEN_STATE_CR=30000ms
IGNORE_EXCEPTION_CR1=com.bac.lib.datapower.v2.exception.AuthenticationException
IGNORE_EXCEPTION_CR2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
SLIDING_WINDOW_SIZE_HN=10
MINIMUM_NUMBER_OF_CALLS_HN=10
FAILURE_RATE_THRESHOLD_HN=50
PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE_HN=5
WAIT_DURATION_IN_OPEN_STATE_HN=30000ms
IGNORE_EXCEPTION_HN1=com.bac.lib.datapower.v2.exception.AuthenticationException
IGNORE_EXCEPTION_HN2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
SLIDING_WINDOW_SIZE_NI=10
MINIMUM_NUMBER_OF_CALLS_NI=10
FAILURE_RATE_THRESHOLD_NI=50
PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE_NI=5
WAIT_DURATION_IN_OPEN_STATE_NI=30000ms
IGNORE_EXCEPTION_NI1=com.bac.lib.datapower.v2.exception.AuthenticationException
IGNORE_EXCEPTION_NI2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
SLIDING_WINDOW_SIZE_GT=10
MINIMUM_NUMBER_OF_CALLS_GT=10
FAILURE_RATE_THRESHOLD_GT=50
PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE_GT=5
WAIT_DURATION_IN_OPEN_STATE_GT=30000ms
IGNORE_EXCEPTION_GT1=com.bac.lib.datapower.v2.exception.AuthenticationException
IGNORE_EXCEPTION_GT2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
SLIDING_WINDOW_SIZE_SV=10
MINIMUM_NUMBER_OF_CALLS_SV=10
FAILURE_RATE_THRESHOLD_SV=50
PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE_SV=5
WAIT_DURATION_IN_OPEN_STATE_SV=30000ms
IGNORE_EXCEPTION_SV1=com.bac.lib.datapower.v2.exception.AuthenticationException
IGNORE_EXCEPTION_SV2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
SLIDING_WINDOW_SIZE_PA=10
MINIMUM_NUMBER_OF_CALLS_PA=10
FAILURE_RATE_THRESHOLD_PA=50
PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE_PA=5
WAIT_DURATION_IN_OPEN_STATE_PA=30000ms
IGNORE_EXCEPTION_PA1=com.bac.lib.datapower.v2.exception.AuthenticationException
IGNORE_EXCEPTION_PA2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
SLIDING_WINDOW_SIZE_DEFAULT=10
MINIMUM_NUMBER_OF_CALLS_DEFAULT=10
FAILURE_RATE_THRESHOLD_DEFAULT=50
PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE_DEFAULT=5
WAIT_DURATION_IN_OPEN_STATE_DEFAULT=30000ms
IGNORE_EXCEPTION_DEFAULT1=com.bac.lib.datapower.v2.exception.AuthenticationException
IGNORE_EXCEPTION_DEFAULT2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
#RESILIENCE - Retry config
RETRY_MAX_ATTEMPTS_CR=3
RETRY_WAIT_DURATION_CR=100ms
RETRY_IGNORE_EXCEPTION_CR1=com.bac.lib.datapower.v2.exception.AuthenticationException
RETRY_IGNORE_EXCEPTION_CR2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
RETRY_MAX_ATTEMPTS_HN=3
RETRY_WAIT_DURATION_HN=100ms
RETRY_IGNORE_EXCEPTION_HN1=com.bac.lib.datapower.v2.exception.AuthenticationException
RETRY_IGNORE_EXCEPTION_HN2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
RETRY_MAX_ATTEMPTS_NI=3
RETRY_WAIT_DURATION_NI=100ms
RETRY_IGNORE_EXCEPTION_NI1=com.bac.lib.datapower.v2.exception.AuthenticationException
RETRY_IGNORE_EXCEPTION_NI2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
RETRY_MAX_ATTEMPTS_GT=3
RETRY_WAIT_DURATION_GT=100ms
RETRY_IGNORE_EXCEPTION_GT1=com.bac.lib.datapower.v2.exception.AuthenticationException
RETRY_IGNORE_EXCEPTION_GT2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
RETRY_MAX_ATTEMPTS_SV=3
RETRY_WAIT_DURATION_SV=100ms
RETRY_IGNORE_EXCEPTION_SV1=com.bac.lib.datapower.v2.exception.AuthenticationException
RETRY_IGNORE_EXCEPTION_SV2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
RETRY_MAX_ATTEMPTS_PA=3
RETRY_WAIT_DURATION_PA=100ms
RETRY_IGNORE_EXCEPTION_PA1=com.bac.lib.datapower.v2.exception.AuthenticationException
RETRY_IGNORE_EXCEPTION_PA2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
RETRY_MAX_ATTEMPTS_DEFAULT=3
RETRY_WAIT_DURATION_DEFAULT=100ms
RETRY_IGNORE_EXCEPTION_DEFAULT1=com.bac.lib.datapower.v2.exception.AuthenticationException
RETRY_IGNORE_EXCEPTION_DEFAULT2=com.bac.lib.datapower.v2.exception.TokenUnauthorizedException
#IMMUTABILITY
IMMUTABILITY_ENABLED=false
SESSION_KEY_HEADER_NAME=X-Custom-Session-Key
SIGNATURE_HEADER_NAME=request-signature
URL_API=https://api-app-dev.baccredomatic.com
## FLAGS METRICS
DYNATRACE_ENABLE=true
#LIST_REGEX
INVESTMENT_FUNDS=^F[0-9]+$
#ALIAS DP
PROXY_OAUTH_URL=https://mobiledev.services.corp.redbac.com/proxy/token
PROXY_SERVICE_URL=https://mobiledev.services.corp.redbac.com/proxy/
DP_ALIAS_SERVICE=sbeuserproductsdetail.web/webapi/v2/product-alias