#!/bin/bash

# Run Checkstyle checks using the Maven Checkstyle Plugin
mvn checkstyle:check

if [ $? -ne 0 ]; then
    echo "***Aborting commit. Checkstyle failed.***"
    exit 1
fi

# Run Maven clean and test goals
mvn clean test

# If the tests fail, abort the commit
if [ $? -ne 0 ]; then
    echo "***Aborting commit. Tests failed.***"
    exit 1
fi